input_dataset:
  name: random_install_multiBC_20convos
  subset: all

n_conversations: 20

parser:
  model: openai/gpt-4o
  temperature: 0.0

annotator:
  model: openai/gpt-4o
  context_mode: interval
  num_context_turns: 5
  class_structure: tiered
  temperature: 0.0

