input_dataset:
  name: HLQC_balanced
  subset: lowconf

n_conversations: null

parser:
  model: gpt-4o-2024-08-06
  temperature: 0.0

annotator:
  model: gpt-4.1-2025-04-14
  context_mode: interval
  num_context_turns: 3
  class_structure: tiered
  temperature: 0.0

