input_dataset:
  name: MIV6.3A
  subset: lowconf

n_conversations: 10

parser:
  model: gpt-4o-2024-08-06
  temperature: 0.0

annotator:
  model: gpt-4o-2024-08-06
  context_mode: interval
  num_context_turns: 5
  class_structure: tiered
  temperature: 0.0

