method: compare

input_dataset:
  name: MIV6.3A
  subset: lowconf

n_conversations: 10

annotated:
  model: gemma-3-12B-it-qat.gguf
  context_mode: interval
  num_context_turns: 10
  class_structure: tiered
  temperature: 0.0
